---
http_interactions:
- request:
    method: post
    uri: https://api.stripe.com/v1/customers/cus_LpHRYgxReYHx5I/sources
    body:
      encoding: UTF-8
      string: source=4242424242424242
    headers:
      User-Agent:
      - Stripe/v1 RubyBindings/6.2.0
      Authorization:
      - Bearer sk_test_51Kz1xcIm6aRqt2RHGvuLqZEYSmSPEqMIWtVu6TxO51xtb057Sg0tUR0Su0yOFIcjEiXXr6GTYEDx2GYrHUNvf5F200Xjx20oPR
      Content-Type:
      - application/x-www-form-urlencoded
      X-Stripe-Client-Telemetry:
      - '{"last_request_metrics":{"request_id":"req_jEbO5RVnyY8At7","request_duration_ms":3}}'
      X-Stripe-Client-User-Agent:
      - '{"bindings_version":"6.2.0","lang":"ruby","lang_version":"2.7.5 p203 (2021-11-24)","platform":"x86_64-darwin21","engine":"ruby","publisher":"stripe","uname":"Darwin
        Apples-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05
        PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64","hostname":"Apples-MacBook-Pro.local"}'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Server:
      - nginx
      Date:
      - Mon, 06 Jun 2022 11:37:49 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '235'
      Connection:
      - keep-alive
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - GET, POST, HEAD, OPTIONS, DELETE
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required
      Access-Control-Max-Age:
      - '300'
      Cache-Control:
      - no-cache, no-store
      Idempotency-Key:
      - 46ab411b-864b-44eb-9b68-8a00b741d287
      Original-Request:
      - req_1V0R93H5O5WdTD
      Request-Id:
      - req_1V0R93H5O5WdTD
      Stripe-Should-Retry:
      - 'false'
      Stripe-Version:
      - '2020-08-27'
      Strict-Transport-Security:
      - max-age=31556926; includeSubDomains; preload
    body:
      encoding: UTF-8
      string: |
        {
          "error": {
            "code": "resource_missing",
            "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
            "message": "No such token: '4242424242424242'",
            "param": "source",
            "type": "invalid_request_error"
          }
        }
  recorded_at: Mon, 06 Jun 2022 11:37:48 GMT
recorded_with: VCR 6.1.0
